name: Compile Examples

on:
  push:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "examples/**"
      - "src/**"
  pull_request:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "examples/**"
      - "src/**"
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest

    env:
      SKETCHES_REPORTS_PATH: sketches-reports

    strategy:
      fail-fast: false

      matrix:
        board:
          - fqbn: arduino:avr:mega
            platforms: |
              - name: arduino:avr
            libraries: |
              - source-path: ./
              - name: CRC
              - name: TelnetStream
              - name: Ethernet
            sketch-paths: |
              - examples/BasicEthernet
              - examples/SineGeneratorEthernet
              - examples/SineGeneratorAndCommandsEthernet
              - examples/CommandsEthernet
              - examples/BridgeEthernet
              - examples/WriteModesEthernet
              - examples/SignalNamesInFlashLessRAMUsage
            artifact-name-suffix: arduino-avr-mega
          - fqbn: arduino:esp32:nano_nora
            platforms: |
              - name: arduino:esp32
            libraries: |
              - source-path: ./
              - name: CRC
              - name: TelnetStream
            sketch-paths: |
              - examples/SineGeneratorWiFi
            artifact-name-suffix: arduino-esp32-nano_nora
          - fqbn: arduino:renesas_uno:unor4wifi
            platforms: |
              - name: arduino:renesas_uno
            libraries: |
              - source-path: ./
              - name: CRC
              - name: TelnetStream
            sketch-paths: |
              - examples/SineGeneratorWiFiS3
              - examples/TimeStampModesWiFiS3
            artifact-name-suffix: arduino-renesas_uno-unor4wifi

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.board.fqbn }}
          platforms: ${{ matrix.board.platforms }}
          libraries: ${{ matrix.board.libraries }}
          sketch-paths: ${{ matrix.board.sketch-paths }}
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Save sketches report as workflow artifact
        uses: actions/upload-artifact@v7
        with:
          if-no-files-found: error
          path: ${{ env.SKETCHES_REPORTS_PATH }}
          name: sketches-report-${{ matrix.board.artifact-name-suffix }}
